jira:
  base_url_env: "JIRA_BASE_URL"
  ca_bundle_env: "JIRA_CA_BUNDLE"
  pat_env: "JIRA_PAT"
  page_size: 100
  parallelism: 2
  validate_query: true

scopes:
  - project: "ASPSCLM"
    issue_types:
      - name: "Feature"
        fields:
          - "summary"
          - "issuetype"
          - "priority"
          - "labels"
          - "assignee"
          - "components"
          - "fixVersions"
          - "issuelinks"
      - name: "Bug"
        fields:
          - "summary"
          - "issuetype"
          - "priority"
          - "labels"
          - "assignee"
          - "components"
          - "fixVersions"
          - "issuelinks"

windows:
  initial_days: 90
  safety_skew_s: 60

database:
  dsn_env: "DATABASE_URL"

output:
  print_only_env: "JIRA_PRINT_ONLY"
  print_only: false
